name: build PDF

on: 
  push:
  pull_request:

permissions:
  contents: read
  # Needed for the 'trilom/file-changes-action' action
  pull-requests: read

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: [self-hosted, Windows]
    timeout-minutes: 5
    
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: build PDF
      shell: powershell
      working-directory: ${{github.workspace}}
      run: |
        function Run-Block-With-Error($block) {
          $ErrorActionPreference="Stop"
          Invoke-Command -ScriptBlock $block
        }
        Run-Block-With-Error {python.exe export_book.py; pdflatex book.tex; bibtex book; pdflatex book.tex; pdflatex book.tex}
        mv book.pdf perf-book.pdf
    
    - uses: actions/upload-artifact@v3
      with:
        name: Performance Analysis and Tuning on Modern CPUs
        path: perf-book.pdf
